create database kishore;
show databases;
use kishore;
CREATE TABLE USERS(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
AGE INT NOT NULL,
PRIMARY KEY (ID)
);
SHOW TABLES;
DESCRIBE USERS;
ALTER TABLE USERS ADD GENDER VARCHAR(10) NOT NULL AFTER AGE;
ALTER TABLE USERS
 ADD CITY VARCHAR(10) NOT NULL,
 ADD CONTACT VARCHAR (10) NOT NULL;
 ALTER TABLE USERS MODIFY CONTACT VARCHAR (35) NOT NULL;
ALTER TABLE USERS RENAME TO STUDENTS;
DESCRIBE STUDENTS;



SELECT * FROM STUDENTS;
INSERT INTO STUDENTS VALUES(NULL,'RAM',25,'MALE','NAGERCOIL','9585535422');
INSERT INTO STUDENTS(NAME,AGE,GENDER,CITY,CONTACT) VALUES('KISHORE',22,'MALE','KUMARI','9360629830');
INSERT INTO STUDENTS(NAME,AGE,GENDER,CITY,CONTACT) VALUES('SK',21,'MALE','KOTTAR','9360629830'),('BABU',25,'MALE','HYDERABAD','9360629830'),('SRUTI',30,'FEMALE','CHENNAI','9360629830');
DELETE FROM STUDENTS WHERE ID=4;
UPDATE STUDENTS SET CITY='HOSUR', CONTACT='6513156566' WHERE ID =2;

TRUNCATE TABLE STUDENTS;
INSERT INTO STUDENTS(NAME,AGE,GENDER,CITY,CONTACT) VALUES('SK',20,'MALE','KOTTAR','9360629830'),('BABU',19,'MALE','HYDERBAD','9360629830'),('SRUTI',18,'FEMALE','CHENNAI','9360629830'),('SK',22,'MALE','KOTTAR','9360629830'),('BABU',22,'MALE','HYDERBAD','9360629830'),('SRUTI',22,'FEMALE','CHENNAI','9360629830'),('SK',20,'MALE','KOTTAR','9360629830'),('BABU',22,'MALE','HYDERBAD','9360629830'),('SRUTI',22,'FEMALE','CHENNAI','9360629830'),('SK',25,'MALE','KOTTAR','9360629830'),('BABU',28,'MALE','HYDERBAD','9360629830'),('SRUTI',22,'FEMALE','CHENNAI','9360629830'),('SK',29,'MALE','KOTTAR','9360629830'),('BABU',27,'MALE','HYDERBAD','9360629830'),('SRUTI',22,'FEMALE','CHENNAI','9360629830');
SELECT NAME, AGE FROM STUDENTS;
SELECT NAME, AGE,CITY FROM STUDENTS WHERE CITY='HYDERBAD';
SELECT NAME, AGE,CITY FROM STUDENTS WHERE CITY='KOTTAR' AND AGE>=22;
SELECT * FROM STUDENTS;
SELECT NAME, AGE,CITY FROM STUDENTS WHERE CITY='CHENNAI' AND AGE>=22;
SELECT NAME, AGE,CITY FROM STUDENTS WHERE CITY='HYDERBAD' AND AGE<=22;
SELECT NAME ,AGE FROM STUDENTS;
SELECT NAME ,AGE,CITY FROM STUDENTS WHERE CITY='CHENNAI' OR CITY='KOTTAR';
SELECT NAME ,AGE,CITY FROM STUDENTS WHERE(CITY='CHENNAI' OR CITY='KOTTAR')AND AGE>=22 ORDER BY CITY;
SELECT CITY FROM STUDENTS;
SELECT DISTINCT CITY FROM STUDENTS;
SELECT COUNT(CITY) FROM STUDENTS;
SELECT COUNT( DISTINCT CITY) FROM STUDENTS;
SELECT COUNT( DISTINCT CITY) AS TOTAL FROM STUDENTS;
SELECT * FROM STUDENTS;
SELECT * FROM STUDENTS LIMIT 0,10;
SELECT * FROM STUDENTS LIMIT 10,3;
SELECT * FROM STUDENTS LIMIT 0,1;
SELECT * FROM STUDENTS ORDER BY ID DESC LIMIT 0,1;
SELECT MAX(AGE) FROM STUDENTS;
SELECT MIN(AGE) FROM STUDENTS;
SELECT AVG(AGE) FROM STUDENTS;
SELECT ROUND (AVG(AGE),0 ) FROM STUDENTS;
SELECT SUM(AGE) FROM STUDENTS;
SELECT GENDER,COUNT(ID) AS TOTAL FROM STUDENTS GROUP BY GENDER;
SELECT * FROM STUDENTS;
SELECT CITY,COUNT(ID) AS TOTAL FROM STUDENTS GROUP BY CITY;
SELECT NAME FROM STUDENTS WHERE NAME LIKE 'BA%';
SELECT NAME FROM STUDENTS WHERE NAME LIKE '%TI';
SELECT NAME FROM STUDENTS WHERE NAME LIKE '%U%';
SELECT * FROM STUDENTS WHERE CITY='KOTTAR' OR CITY='HYDERBAD';
SELECT * FROM STUDENTS WHERE CITY IN ('KOTTAR','CHENNAI'); 
UPDATE STUDENTS SET CITY='CHENKOTTAR', CONTACT='7598212522' WHERE ID=15;
SELECT * FROM STUDENTS WHERE CITY IN ('KOTTAR','CHENNAI'); 
SELECT * FROM STUDENTS WHERE CITY NOT IN ('KOTTAR','CHENNAI'); 
SELECT NAME FROM STUDENTS WHERE NAME NOT LIKE 'BA%';
SELECT NAME,AGE FROM STUDENTS WHERE AGE NOT BETWEEN 15 AND 20;



CREATE TABLE ATTENDANCE(
AID INT NOT NULL AUTO_INCREMENT,
ID INT NOT NULL,
ADATE DATE NOT NULL, 
ASTATUS VARCHAR(10) NOT NULL,
PRIMARY KEY(AID)
);
DESCRIBE ATTENDANCE;
SHOW TABLES;

TRUNCATE TABLE ATTENDANCE;
SELECT * FROM ATTENDANCE;
INSERT INTO ATTENDANCE (ID,ADATE,ASTATUS) VALUES(1024990,'2023-02-14','PASS'),(1024991,'2023-02-15','FAIL'),(1024990,'2023-02-16','PASS'),(1024990,'2023-02-17','FAIL'),(1024991,'2023-02-18','PASS'),(1024990,'2023-02-19','FAIL'),(1024990,'2023-02-20','PASS'),(1024991,'2023-02-21','FAIL'),(1024990,'2023-02-22','PASS'),(1024990,'2023-02-23','FAIL'),(1024990,'2023-02-24','PASS'),(1024991,'2023-02-25','FAIL'),(1024990,'2023-02-26','PASS'),(1024990,'2023-02-27','PASS'),(1024990,'2023-02-28','FAIL'),(1024991,'2023-02-15','FAIL'),(1024991,'2023-02-15','FAIL'),(1024991,'2023-02-15','FAIL'),(1024991,'2023-02-15','PASS'),(1024991,'2023-02-15','FAIL'),(1024991,'2023-02-15','PASS'),(1024991,'2023-02-15','FAIL');
SELECT * FROM ATTENDANCE;
SELECT * FROM STUDENTS;
SELECT * FROM ATTENDANCE WHERE ID=1024990;
SELECT * FROM ATTENDANCE WHERE ID=1024991;
SELECT ID ,COUNT(ADATE) AS WORKING ,
COUNT(IF(ASTATUS='PASS',1,NULL)) AS PRESENT
FROM ATTENDANCE group by ID;


CREATE TABLE EMP(
ID INT NOT NULL auto_increment,
NAME VARCHAR(45) NOT NULL,
DESIGN VARCHAR(45) NOT NULL,
DOJ DATE NOT NULL,
primary key(ID)
);
TRUNCATE TABLE EMP;
SHOW TABLES;
INSERT INTO EMP(NAME,DESIGN,DOJ)VALUES('KISHORE','MANAGER','2019-08-20'),
('MURUGAN','BUSINESS','2019-08-21'),
('VIHITHA','SALES','2019-08-22'),
('SIVAKAMI','CLERK','2019-08-23'),
('SRUTI','LOVE','2019-10-14');

SELECT * FROM EMP;


TRUNCATE TABLE SALARY;
CREATE TABLE SALARY(
SID INT NOT NULL auto_increment,
ID INT NOT NULL,
SDATE DATE NOT NULL,
AMT INT NOT NULL,
PRIMARY KEY(ID)

);


INSERT INTO SALARY(ID,SDATE,AMT)VALUES(1,'2000-08-19',10000),
(2,'2000-08-19',20000),
(3,'2000-08-19',30000),
(4,'2000-08-19',40000);

SELECT * FROM SALARY;
SELECT * FROM EMP;

SELECT EMP.NAME,EMP.DESIGN,SALARY.SDATE,SALARY.AMT FROM EMP INNER JOIN SALARY
ON EMP.ID=SALARY.ID;

SELECT EMP.NAME,EMP.DESIGN,SALARY.SDATE,SALARY.AMT FROM EMP LEFT JOIN SALARY
ON EMP.ID=SALARY.ID;

SELECT EMP.NAME,EMP.DESIGN,SALARY.SDATE,SALARY.AMT FROM EMP RIGHT JOIN SALARY
ON EMP.ID=SALARY.ID;


SELECT * FROM STUDENTS;
SELECT * FROM ATTENDANCE;

SELECT STUDENTS.NAME,ATTENDANCE.ADATE,ATTENDANCE.ASTATUS FROM STUDENTS INNER JOIN ATTENDANCE
ON STUDENTS.ID=ATTENDANCE.AID;


SELECT * FROM STUDENTS;
SELECT DISTINCT CITY FROM STUDENTS;
SELECT NAME ,CITY,(
CASE
WHEN CITY='KOTTAR'THEN 85
WHEN CITY='CHENNAI'THEN 155
WHEN CITY='HYDERBAD'THEN 125
WHEN CITY='CHENKOTTAR'THEN 200
END

)AS AMT FROM STUDENTS ;

/*
CASE END ELSE
*/

SELECT NAME ,CITY,(
CASE
WHEN CITY='KOTTAR'THEN 85
WHEN CITY='CHENNAI'THEN 155
WHEN CITY='HYDERBAD'THEN 125
WHEN CITY='CHENKOTTAR'THEN 200
ELSE 0
END

)AS AMT FROM STUDENTS WHERE CITY='CHENNAI' ;



SELECT * FROM STUDENTS;
SELECT * FROM ATTENDANCE;
SELECT * FROM EMP;


/*
TWO TABLES JOIN
*/


SELECT STUDENTS.NAME ,STUDENTS.AGE,STUDENTS.GENDER,ATTENDANCE.ID,ATTENDANCE.ASTATUS FROM STUDENTS INNER JOIN ATTENDANCE 
ON STUDENTS.ID=ATTENDANCE.AID ;


/*
THREE TABLES JOIN
*/


SELECT STUDENTS.NAME ,STUDENTS.AGE,STUDENTS.GENDER,ATTENDANCE.ID,ATTENDANCE.ASTATUS,EMP.DESIGN FROM STUDENTS INNER JOIN ATTENDANCE 
ON STUDENTS.ID=ATTENDANCE.AID INNER JOIN EMP ON STUDENTS.ID=EMP.ID;


CREATE TABLE MARKS (
ID INT NOT NULL AUTO_INCREMENT,
M1 INT NOT NULL,
M2 INT NOT NULL,
M3 INT NOT NULL,
M4 INT NOT NULL,
M5 INT NOT NULL,
PRIMARY KEY (ID)
);
DESCRIBE MARKS;

INSERT INTO MARKS(M1,M2,M3,M4,M5)VALUES(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96),(98,97,94,95,96);
SELECT * FROM MARKS;


/*
THREE TABLES JOIN
*/

SELECT STUDENTS.NAME ,STUDENTS.AGE,STUDENTS.GENDER,ATTENDANCE.ID,ATTENDANCE.ASTATUS,EMP.DESIGN,MARKS.M1,MARKS.M2,MARKS.M3,MARKS.M4,MARKS.M5 FROM STUDENTS INNER JOIN ATTENDANCE 
ON STUDENTS.ID=ATTENDANCE.AID INNER JOIN EMP ON STUDENTS.ID=EMP.ID  INNER JOIN MARKS ON STUDENTS.ID=MARKS.ID;

/*
THREE TABLES JOIN  AND HAVING ADDITION,
*/


SELECT STUDENTS.NAME ,STUDENTS.AGE,STUDENTS.GENDER,ATTENDANCE.ID,ATTENDANCE.ASTATUS,MARKS.M1,MARKS.M2,MARKS.M3,MARKS.M4,MARKS.M5, (MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5) AS TOTAL  FROM STUDENTS INNER JOIN ATTENDANCE 
ON STUDENTS.ID=ATTENDANCE.AID INNER JOIN MARKS  ON STUDENTS.ID=MARKS.ID;



/*
THREE TABLES JOIN  AND HAVING AVERAGE,
*/
SELECT STUDENTS.NAME ,STUDENTS.AGE,STUDENTS.GENDER,ATTENDANCE.ID,ATTENDANCE.ASTATUS,MARKS.M1,MARKS.M2,MARKS.M3,MARKS.M4,MARKS.M5, (MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5) AS TOTAL,ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2) AS AVERAGE  FROM STUDENTS INNER JOIN ATTENDANCE 
ON STUDENTS.ID=ATTENDANCE.AID INNER JOIN MARKS  ON STUDENTS.ID=MARKS.ID;

/*
THREE TABLES JOIN  AND HAVING AVERAGE
*/
SELECT STUDENTS.NAME ,STUDENTS.AGE,STUDENTS.GENDER,ATTENDANCE.ID,ATTENDANCE.ASTATUS,MARKS.M1,MARKS.M2,MARKS.M3,MARKS.M4,MARKS.M5, (MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5) AS TOTAL,ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2) AS AVERAGE  FROM STUDENTS INNER JOIN ATTENDANCE 
ON STUDENTS.ID=ATTENDANCE.AID INNER JOIN MARKS  ON STUDENTS.ID=MARKS.ID;


/*
THREE TABLES JOIN  AND HAVING RESULT CASE END
*/

SELECT STUDENTS.NAME ,STUDENTS.AGE,STUDENTS.GENDER,ATTENDANCE.ID,ATTENDANCE.ASTATUS,MARKS.M1,MARKS.M2,MARKS.M3,MARKS.M4,MARKS.M5, (MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5) AS TOTAL,ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2) AS AVERAGE ,
CASE
WHEN MARKS.M1>=35 AND MARKS.M2 >=35 AND MARKS.M3 >=35 AND MARKS.M4 >=35 AND MARKS.M5 >=35 THEN 'PROMOTE'
ELSE 'DEPROMOTE'
END AS RESULT
 FROM STUDENTS INNER JOIN ATTENDANCE 
ON STUDENTS.ID=ATTENDANCE.AID INNER JOIN MARKS  ON STUDENTS.ID=MARKS.ID;



/*
THREE TABLES JOIN  AND HAVING RESULT CASE END , RESULT,GRADE
*/

SELECT STUDENTS.NAME ,STUDENTS.AGE,STUDENTS.GENDER,ATTENDANCE.ID,ATTENDANCE.ASTATUS,MARKS.M1,MARKS.M2,MARKS.M3,MARKS.M4,MARKS.M5, (MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5) AS TOTAL,ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2) AS AVERAGE ,
CASE
WHEN MARKS.M1>=35 AND MARKS.M2 >=35 AND MARKS.M3 >=35 AND MARKS.M4 >=35 AND MARKS.M5 >=35 THEN 'PROMOTE'
ELSE 'DEPROMOTE'
END AS RESULT,
CASE
WHEN MARKS.M1>=35 AND MARKS.M2 >=35 AND MARKS.M3 >=35 AND MARKS.M4 >=35 AND MARKS.M5 >=35 THEN 
CASE
  WHEN  ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2) >=150 AND ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2)<=200 THEN 'A'
WHEN  ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2) >=130 AND ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2)<=149 THEN 'B'
ELSE 'C'
END
ELSE 'NO GRADE'
END AS GRADE
 FROM STUDENTS INNER JOIN ATTENDANCE 
ON STUDENTS.ID=ATTENDANCE.AID INNER JOIN MARKS  ON STUDENTS.ID=MARKS.ID  ;

/*
THREE TABLES JOIN  AND HAVING RESULT CASE END , RESULT,GRADE,WHERE FROM ONE,HAVING(AND,HAVING USING)
*/


SELECT STUDENTS.NAME ,STUDENTS.AGE,STUDENTS.GENDER,ATTENDANCE.ID,ATTENDANCE.ASTATUS,MARKS.M1,MARKS.M2,MARKS.M3,MARKS.M4,MARKS.M5, (MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5) AS TOTAL,ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2) AS AVERAGE ,
CASE
WHEN MARKS.M1>=35 AND MARKS.M2 >=35 AND MARKS.M3 >=35 AND MARKS.M4 >=35 AND MARKS.M5 >=35 THEN 'PROMOTE'
ELSE 'DEPROMOTE'
END AS RESULT,
CASE
WHEN MARKS.M1>=35 AND MARKS.M2 >=35 AND MARKS.M3 >=35 AND MARKS.M4 >=35 AND MARKS.M5 >=35 THEN 
CASE
  WHEN  ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2) >=150 AND ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2)<=200 THEN 'A'
WHEN  ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2) >=130 AND ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2)<=149 THEN 'B'
ELSE 'C'
END
ELSE 'NO GRADE'
END AS GRADE
 FROM STUDENTS INNER JOIN ATTENDANCE 
ON STUDENTS.ID=ATTENDANCE.AID INNER JOIN MARKS  ON STUDENTS.ID=MARKS.ID WHERE GENDER='MALE' AND ASTATUS='PASS' HAVING GRADE='A'  AND (AVERAGE>=150 AND AVERAGE<=200) ;


/*
view time
*/




CREATE VIEW REPORTS AS 
SELECT STUDENTS.NAME ,STUDENTS.AGE,STUDENTS.GENDER,ATTENDANCE.ID,ATTENDANCE.ASTATUS,MARKS.M1,MARKS.M2,MARKS.M3,MARKS.M4,MARKS.M5, (MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5) AS TOTAL,ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2) AS AVERAGE ,
CASE
WHEN MARKS.M1>=35 AND MARKS.M2 >=35 AND MARKS.M3 >=35 AND MARKS.M4 >=35 AND MARKS.M5 >=35 THEN 'PROMOTE'
ELSE 'DEPROMOTE'
END AS RESULT,
CASE
WHEN MARKS.M1>=35 AND MARKS.M2 >=35 AND MARKS.M3 >=35 AND MARKS.M4 >=35 AND MARKS.M5 >=35 THEN 
CASE
  WHEN  ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2) >=150 AND ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2)<=200 THEN 'A'
WHEN  ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2) >=130 AND ROUND((MARKS.M1+MARKS.M2+MARKS.M3+MARKS.M4+MARKS.M5)/3,2)<=149 THEN 'B'
ELSE 'C'
END
ELSE 'NO GRADE'
END AS GRADE
 FROM STUDENTS INNER JOIN ATTENDANCE 
ON STUDENTS.ID=ATTENDANCE.AID INNER JOIN MARKS  ON STUDENTS.ID=MARKS.ID  ;

SHOW TABLES;
SHOW FULL tables;

SELECT * FROM REPORTS;
SELECT NAME,ID,ASTATUS FROM REPORTS WHERE GENDER='FEMALE';


DROP VIEW REPORTS;




SELECT * FROM REPORTS;
SELECT * FROM STUDENTS;
SELECT * FROM MARKS;

SELECT  STUDENTS.NAME,STUDENTS.GENDER,STUDENTS.CITY,MARKS.M1,MARKS.M2,MARKS.M3,MARKS.M4,MARKS.M5
FROM STUDENTS INNER JOIN MARKS ON STUDENTS.ID=MARKS.ID;

UPDATE MARKS INNER JOIN  STUDENTS ON STUDENTS .ID=MARKS.ID
SET MARKS.M1=100,MARKS.M2=100 WHERE GENDER='MALE';




/*
TRIGGERS
*/



SHOW FULL TABLES;


