create database babu;
drop database babu;
create database kishore;
show databases;
use kishore;
CREATE TABLE USERS(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
AGE INT NOT NULL,
PRIMARY KEY (ID)
);
SHOW TABLES;
DESCRIBE USERS;
ALTER TABLE USERS ADD GENDER VARCHAR(10) NOT NULL AFTER AGE;
ALTER TABLE USERS
 ADD CITY VARCHAR(10) NOT NULL,
 ADD CONTACT VARCHAR (10) NOT NULL;
 ALTER TABLE USERS MODIFY CONTACT VARCHAR (35) NOT NULL;
ALTER TABLE USERS RENAME TO STUDENTS;
DESCRIBE STUDENTS;



SELECT * FROM STUDENTS;
INSERT INTO STUDENTS VALUES(NULL,'RAM',25,'MALE','NAGERCOIL','9585535422');
INSERT INTO STUDENTS(NAME,AGE,GENDER,CITY,CONTACT) VALUES('KISHORE',22,'MALE','KUMARI','9360629830');
INSERT INTO STUDENTS(NAME,AGE,GENDER,CITY,CONTACT) VALUES('SK',22,'MALE','KOTTAR','9360629830'),('BABU',22,'MALE','HYDERBAD','9360629830'),('SRUTI',22,'FEMALE','CHENNAI','9360629830');
DELETE FROM STUDENTS WHERE ID=4;
UPDATE STUDENTS SET CITY='HOSUR', CONTACT='6513156566' WHERE ID =2;

